#ifndef _PROJECTOR_H
#define _PROJECTOR_H

#include <stdint.h>


#define GST_BLANK 0
#define GST_VIDEOTESTSRC 1
#define GST_VIDEOTESTSRC_CUBED 2


#define GST_LIBVISUAL_FIRST 6
#define GST_LIBVISUAL_WAVE_RADIO 6
#define GST_LIBVISUAL_WAVE 7
#define GST_LIBVISUAL_WAVEV 8
#define GST_LIBVISUAL_JAKDAWV 9
#define GST_LIBVISUAL_INFINITE 10
#define GST_LIBVISUAL_JAKDAW 11
#define GST_LIBVISUAL_OINKSIE 12
#define GST_GOOM 13
#define GST_GOOM2K1 14
#define GST_LIBVISUAL_LAST 14


#define GST_MOVIE_FIRST 50

#define GST_MOVIE_80s_FIRST  (GST_MOVIE_FIRST)
#define GST_MOVIE_80s_LAST  (GST_MOVIE_80s_FIRST + 8 - 1)
 
#define GST_MOVIE_FAST_FIRST   (GST_MOVIE_80s_LAST + 1)
#define GST_MOVIE_FAST_LAST (GST_MOVIE_FAST_FIRST + 10 - 1)

#define GST_MOVIE_SLOW_FIRST  (GST_MOVIE_FAST_LAST + 1)
#define  GST_MOVIE_SLOW_LAST  (GST_MOVIE_SLOW_FIRST + 13 - 1)

#define GST_MOVIE_OTHER_FIRST  (GST_MOVIE_SLOW_LAST + 1)
#define GST_MOVIE_OTHER_LAST  (GST_MOVIE_OTHER_FIRST + 8 - 1)

#define GST_MOVIE_LAST GST_MOVIE_OTHER_LAST




#endif